version: '3.8'

services:
  db:
    image: postgres:14.0-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    
  app:
    image: us-docker.pkg.dev/genuine-polymer-165712/codecov/codecov-slack-app:latest
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      RUN_ENV: LOCAL
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db 
    env_file:
      - .env

volumes:
  db_data:
